export const USER_LOGIN_REQUEST = 'USER_LOGIN_REQUEST'
export const USER_LOGGEDIN_SUCCESS = 'USER_LOGGEDIN_SUCCESS'
export const USER_LOGGEDIN_FAIL = 'USER_LOGGEDIN_FAIL'
export const USER_LOGIN_INPROGRESS = 'USER_LOGIN_INPROGRESS'
